version: '3.4'

services:
  steammarketplace.authorizationwebapplication:
    image: ${DOCKER_REGISTRY-}steammarketplaceauthorizationwebapplication
    build:
      context: '.'
      dockerfile: 'SteamMarketplace.AuthorizationWebApplication/Dockerfile'
  steammarketplace.authorizationwebapplication.seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
  steammarketplace.resourcewebapplication:
    image: ${DOCKER_REGISTRY-}steammarketplaceresourcewebapplication
    build:
      context: '.'
      dockerfile: 'SteamMarketplace.ResourceWebApplication/Dockerfile'
  steammarketplace.resourcewebapplication.seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
  steammarketplace.vuejsapp:
    image: steammarketplacevuejsapp
    build:
        context: 'steam-marketplace-vue-js-app/'
        dockerfile: 'Dockerfile'
  steammarketplace.postgres:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_DB: SteamMarketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
    volumes:
      - ./steammarketplace.postgres:/var/lib/postgresql/data
  steammarketplace.postgres.pgadmin:
    image: dpage/pgadmin4:6.11
    environment:
      PGADMIN_DEFAULT_EMAIL: "andrey.levchenko.2001@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "sa"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./steammarketplace.postgres.pgadmin:/var/lib/pgadmin
    links:
       - "steammarketplace.postgres:pgsql-server"
    restart: unless-stopped
  proxy:
    image: nginx:mainline
