version: '3.4'

services:
  steammarketplace.authorizationwebapplication:
    image: ${DOCKER_REGISTRY-}steammarketplaceauthorizationwebapplication
    build:
      context: '.'
      dockerfile: 'SteamMarketplace.AuthorizationWebApplication/Dockerfile'
  steammarketplace.authorizationwebapplication.seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
  steammarketplace.resourcewebapplication:
    image: ${DOCKER_REGISTRY-}steammarketplaceresourcewebapplication
    build:
      context: '.'
      dockerfile: 'SteamMarketplace.ResourceWebApplication/Dockerfile'
  steammarketplace.resourcewebapplication.seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
  steammarketplace.vuejsapp:
    image: steammarketplacevuejsapp
    build:
        context: 'steam-marketplace-vue-js-app/'
        dockerfile: 'Dockerfile'
  steammarketplace.postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: SteamMarketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
    volumes:
      - ./steammarketplace.postgres:/var/lib/postgresql/data
  steammarketplace.postgres.pgadmin:
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "andrey.levchenko.2001@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "sa"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./steammarketplace.postgres.pgadmin:/var/lib/pgadmin
    restart: unless-stopped
  steammarketplace.traefik:
    image: traefik:v2.4
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      # Add folder with dynamic configuration yml
      - ./data/configurations:/configurations
    labels:
      - "traefik.enable=true"
      #- "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`194-67-67-175.cloudvps.regruhosting.ru`)"
      - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"
  steammarketplace.proxy:
    image: nginx:mainline
