version: '3.4'

services:
  steammarketplace.authorizationwebapplication:
    image: ${DOCKER_REGISTRY-}steammarketplaceauthorizationwebapplication
    build:
      context: '/var/projects/SteamMarketplace/docker-compose/'
      dockerfile: SteamMarketplace.AuthorizationWebApplication/Dockerfile
  steammarketplace.resourcewebapplication:
    image: ${DOCKER_REGISTRY-}steammarketplaceresourcewebapplication
    build:
      context: '/var/projects/SteamMarketplace/docker-compose/'
      dockerfile: SteamMarketplace.ResourceWebApplication/Dockerfile
  steammarketplace.vuejsapp:
    image: steammarketplacevuejsapp
    build:
        context: '/var/projects/SteamMarketplace/docker-compose/'
        dockerfile: Dockerfile
  steammarketplace.postgres:
    image: postgres:14
    networks:
      - back
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: SteamMarketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/initpg.sh:/docker-entrypoint-initdb.d/initpg.sh
  steammarketplace.postgres.pgadmin:
    image: dpage/pgadmin4:5.7
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 5050
    restart: unless-stopped
