global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "steammarketplace.prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["steammarketplace.prometheus:9090"]

  - job_name: "steammarketplace.node.exporter"
    static_configs:
    - targets: ["steammarketplace.node.exporter:9100"]