--
-- PostgreSQL database dump
--

-- Dumped from database version 14.4
-- Dumped by pg_dump version 14.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Applications" (
    "Id" uuid NOT NULL,
    "SteamId" integer NOT NULL,
    "Name" text
);


ALTER TABLE public."Applications" OWNER TO postgres;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" uuid NOT NULL,
    "CurrencyId" uuid NOT NULL,
    "WalletBalance" numeric(18,6) NOT NULL,
    "RegisteredAt" timestamp without time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- Name: Collections; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Collections" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "RuName" text
);


ALTER TABLE public."Collections" OWNER TO postgres;

--
-- Name: Currencies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Currencies" (
    "Id" uuid NOT NULL,
    "Literal" text NOT NULL,
    "CultureInfoName" text NOT NULL
);


ALTER TABLE public."Currencies" OWNER TO postgres;

--
-- Name: ExchangeRates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ExchangeRates" (
    "Id" uuid NOT NULL,
    "CurrencyId" uuid NOT NULL,
    "Rate" numeric(18,6) NOT NULL,
    "DateTime" timestamp without time zone NOT NULL
);


ALTER TABLE public."ExchangeRates" OWNER TO postgres;

--
-- Name: ItemImages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ItemImages" (
    "Id" uuid NOT NULL,
    "ItemId" uuid NOT NULL,
    "Image" text,
    "Image3d" text,
    "SteamImg" text,
    "Screenshot" text
);


ALTER TABLE public."ItemImages" OWNER TO postgres;

--
-- Name: ItemNesteds; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ItemNesteds" (
    "Id" uuid NOT NULL,
    "ItemId" uuid NOT NULL,
    "ItemNestedId" uuid NOT NULL
);


ALTER TABLE public."ItemNesteds" OWNER TO postgres;

--
-- Name: ItemTypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ItemTypes" (
    "Id" uuid NOT NULL,
    "CSMoneyId" integer NOT NULL,
    "Name" text
);


ALTER TABLE public."ItemTypes" OWNER TO postgres;

--
-- Name: Items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Items" (
    "Id" uuid NOT NULL,
    "ApplicationId" uuid NOT NULL,
    "CollectionId" uuid,
    "QualityId" uuid,
    "RarityId" uuid,
    "TypeId" uuid NOT NULL,
    "AssetId" bigint NOT NULL,
    "CSMoneyId" bigint NOT NULL,
    "Float" real,
    "Name" text,
    "SteamId" text NOT NULL,
    "FullName" text NOT NULL,
    "AddedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."Items" OWNER TO postgres;

--
-- Name: Purchases; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Purchases" (
    "Id" uuid NOT NULL,
    "BuyerId" uuid NOT NULL,
    "SaleId" uuid NOT NULL,
    "Price" numeric(18,6) NOT NULL,
    "PriceUsd" numeric(18,6) NOT NULL,
    "PurchaseAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."Purchases" OWNER TO postgres;

--
-- Name: Qualities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Qualities" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "RuName" text
);


ALTER TABLE public."Qualities" OWNER TO postgres;

--
-- Name: Rarities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Rarities" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "RuName" text
);


ALTER TABLE public."Rarities" OWNER TO postgres;

--
-- Name: Sales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sales" (
    "Id" uuid NOT NULL,
    "SellerId" uuid NOT NULL,
    "ItemId" uuid NOT NULL,
    "Price" numeric(18,6) NOT NULL,
    "PriceUsd" numeric(18,6) NOT NULL,
    "ExposedAt" timestamp without time zone NOT NULL,
    "SoldAt" timestamp without time zone,
    "CancelledAt" timestamp without time zone
);


ALTER TABLE public."Sales" OWNER TO postgres;

--
-- Name: TransactionTypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TransactionTypes" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "RuName" text NOT NULL
);


ALTER TABLE public."TransactionTypes" OWNER TO postgres;

--
-- Name: Transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Transactions" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TypeId" uuid NOT NULL,
    "PurchaseId" uuid,
    "Value" numeric(18,6) NOT NULL,
    "HappenedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."Transactions" OWNER TO postgres;

--
-- Name: UserInventories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserInventories" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ItemId" uuid NOT NULL,
    "AddedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."UserInventories" OWNER TO postgres;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: Applications PK_Applications; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Applications"
    ADD CONSTRAINT "PK_Applications" PRIMARY KEY ("Id");


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Collections PK_Collections; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Collections"
    ADD CONSTRAINT "PK_Collections" PRIMARY KEY ("Id");


--
-- Name: Currencies PK_Currencies; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Currencies"
    ADD CONSTRAINT "PK_Currencies" PRIMARY KEY ("Id");


--
-- Name: ExchangeRates PK_ExchangeRates; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ExchangeRates"
    ADD CONSTRAINT "PK_ExchangeRates" PRIMARY KEY ("Id");


--
-- Name: ItemImages PK_ItemImages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItemImages"
    ADD CONSTRAINT "PK_ItemImages" PRIMARY KEY ("Id");


--
-- Name: ItemNesteds PK_ItemNesteds; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItemNesteds"
    ADD CONSTRAINT "PK_ItemNesteds" PRIMARY KEY ("Id");


--
-- Name: ItemTypes PK_ItemTypes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItemTypes"
    ADD CONSTRAINT "PK_ItemTypes" PRIMARY KEY ("Id");


--
-- Name: Items PK_Items; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "PK_Items" PRIMARY KEY ("Id");


--
-- Name: Purchases PK_Purchases; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Purchases"
    ADD CONSTRAINT "PK_Purchases" PRIMARY KEY ("Id");


--
-- Name: Qualities PK_Qualities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Qualities"
    ADD CONSTRAINT "PK_Qualities" PRIMARY KEY ("Id");


--
-- Name: Rarities PK_Rarities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Rarities"
    ADD CONSTRAINT "PK_Rarities" PRIMARY KEY ("Id");


--
-- Name: Sales PK_Sales; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "PK_Sales" PRIMARY KEY ("Id");


--
-- Name: TransactionTypes PK_TransactionTypes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TransactionTypes"
    ADD CONSTRAINT "PK_TransactionTypes" PRIMARY KEY ("Id");


--
-- Name: Transactions PK_Transactions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id");


--
-- Name: UserInventories PK_UserInventories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserInventories"
    ADD CONSTRAINT "PK_UserInventories" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_AspNetUsers_CurrencyId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUsers_CurrencyId" ON public."AspNetUsers" USING btree ("CurrencyId");


--
-- Name: IX_ExchangeRates_CurrencyId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ExchangeRates_CurrencyId" ON public."ExchangeRates" USING btree ("CurrencyId");


--
-- Name: IX_ItemImages_ItemId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_ItemImages_ItemId" ON public."ItemImages" USING btree ("ItemId");


--
-- Name: IX_ItemNesteds_ItemId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ItemNesteds_ItemId" ON public."ItemNesteds" USING btree ("ItemId");


--
-- Name: IX_ItemNesteds_ItemNestedId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ItemNesteds_ItemNestedId" ON public."ItemNesteds" USING btree ("ItemNestedId");


--
-- Name: IX_Items_ApplicationId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Items_ApplicationId" ON public."Items" USING btree ("ApplicationId");


--
-- Name: IX_Items_CollectionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Items_CollectionId" ON public."Items" USING btree ("CollectionId");


--
-- Name: IX_Items_QualityId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Items_QualityId" ON public."Items" USING btree ("QualityId");


--
-- Name: IX_Items_RarityId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Items_RarityId" ON public."Items" USING btree ("RarityId");


--
-- Name: IX_Items_TypeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Items_TypeId" ON public."Items" USING btree ("TypeId");


--
-- Name: IX_Purchases_BuyerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Purchases_BuyerId" ON public."Purchases" USING btree ("BuyerId");


--
-- Name: IX_Purchases_SaleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Purchases_SaleId" ON public."Purchases" USING btree ("SaleId");


--
-- Name: IX_Sales_ItemId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sales_ItemId" ON public."Sales" USING btree ("ItemId");


--
-- Name: IX_Sales_SellerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sales_SellerId" ON public."Sales" USING btree ("SellerId");


--
-- Name: IX_Transactions_PurchaseId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Transactions_PurchaseId" ON public."Transactions" USING btree ("PurchaseId");


--
-- Name: IX_Transactions_TypeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Transactions_TypeId" ON public."Transactions" USING btree ("TypeId");


--
-- Name: IX_Transactions_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Transactions_UserId" ON public."Transactions" USING btree ("UserId");


--
-- Name: IX_UserInventories_ItemId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserInventories_ItemId" ON public."UserInventories" USING btree ("ItemId");


--
-- Name: IX_UserInventories_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserInventories_UserId" ON public."UserInventories" USING btree ("UserId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUsers FK_AspNetUsers_Currencies_CurrencyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "FK_AspNetUsers_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES public."Currencies"("Id") ON DELETE CASCADE;


--
-- Name: ExchangeRates FK_ExchangeRates_Currencies_CurrencyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ExchangeRates"
    ADD CONSTRAINT "FK_ExchangeRates_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES public."Currencies"("Id") ON DELETE CASCADE;


--
-- Name: ItemImages FK_ItemImages_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItemImages"
    ADD CONSTRAINT "FK_ItemImages_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE CASCADE;


--
-- Name: ItemNesteds FK_ItemNesteds_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItemNesteds"
    ADD CONSTRAINT "FK_ItemNesteds_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id");


--
-- Name: ItemNesteds FK_ItemNesteds_Items_ItemNestedId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ItemNesteds"
    ADD CONSTRAINT "FK_ItemNesteds_Items_ItemNestedId" FOREIGN KEY ("ItemNestedId") REFERENCES public."Items"("Id");


--
-- Name: Items FK_Items_Applications_ApplicationId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_Applications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES public."Applications"("Id") ON DELETE CASCADE;


--
-- Name: Items FK_Items_Collections_CollectionId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_Collections_CollectionId" FOREIGN KEY ("CollectionId") REFERENCES public."Collections"("Id");


--
-- Name: Items FK_Items_ItemTypes_TypeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_ItemTypes_TypeId" FOREIGN KEY ("TypeId") REFERENCES public."ItemTypes"("Id") ON DELETE CASCADE;


--
-- Name: Items FK_Items_Qualities_QualityId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_Qualities_QualityId" FOREIGN KEY ("QualityId") REFERENCES public."Qualities"("Id");


--
-- Name: Items FK_Items_Rarities_RarityId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_Rarities_RarityId" FOREIGN KEY ("RarityId") REFERENCES public."Rarities"("Id");


--
-- Name: Purchases FK_Purchases_AspNetUsers_BuyerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Purchases"
    ADD CONSTRAINT "FK_Purchases_AspNetUsers_BuyerId" FOREIGN KEY ("BuyerId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Purchases FK_Purchases_Sales_SaleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Purchases"
    ADD CONSTRAINT "FK_Purchases_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES public."Sales"("Id");


--
-- Name: Sales FK_Sales_AspNetUsers_SellerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "FK_Sales_AspNetUsers_SellerId" FOREIGN KEY ("SellerId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Sales FK_Sales_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "FK_Sales_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE CASCADE;


--
-- Name: Transactions FK_Transactions_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "FK_Transactions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Transactions FK_Transactions_Purchases_PurchaseId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "FK_Transactions_Purchases_PurchaseId" FOREIGN KEY ("PurchaseId") REFERENCES public."Purchases"("Id");


--
-- Name: Transactions FK_Transactions_TransactionTypes_TypeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "FK_Transactions_TransactionTypes_TypeId" FOREIGN KEY ("TypeId") REFERENCES public."TransactionTypes"("Id") ON DELETE CASCADE;


--
-- Name: UserInventories FK_UserInventories_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserInventories"
    ADD CONSTRAINT "FK_UserInventories_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: UserInventories FK_UserInventories_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserInventories"
    ADD CONSTRAINT "FK_UserInventories_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

